GlobalVars:
  AllowedVariables:
    - $message_symbols

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 25

AllCops:
  Exclude:
    - 'node_modules/**/*'
