GlobalVars:
  AllowedVariables:
    - $message_symbols

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 80
  # disable for regex-only lines
  IgnoredPatterns: ['(\A|\s)%r{.*}']

Metrics/AbcSize:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'node_modules/**/*'


