GlobalVars:
  AllowedVariables:
    - $sess_var
    - $message_symbols

Metrics/AbcSize:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  # for helper_functions.rb
  # some lines have to be longer than 85 due to URLs
  Max: 85
