GlobalVars:
  # allow these *only*, as it avoids adding needless complexity
  AllowedVariables:
    - $markdown # instead of singleton

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 80
  # disable for regex-only lines
  IgnoredPatterns: ['(\A|\s)%r{.*}']

Metrics/AbcSize:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'docs/**/*'
